# Generated by physio-ecosystem/publishing/generate_core_compat.R -- do not edit.

#' PhysioCore: Compatibility Layer for the PhysioExperiment Data Model
#'
#' Compatibility package. The shared data model that used to live here -- the
#' `PhysioExperiment` class and the containers for multiple streams, repeated
#' sessions and cohorts -- now lives in the \pkg{PhysioExperiment} package. Every
#' public symbol is re-exported from there unchanged, so that
#' `library(PhysioCore)`, `PhysioCore::fn()` and `S4` objects saved while the
#' classes were defined here all keep working. New code should depend on
#' \pkg{PhysioExperiment} directly.
#'
#' @section Constructors and containers:
#' `PhysioExperiment()`, `PhysioEvents()`, `MultiPhysioExperiment()`,
#' `MultiRatePhysioExperiment()`, `PhysioLongitudinal()`, `PhysioCohort()`.
#'
#' @section Core accessors:
#' `samplingRate()`, `nChannels()`, `duration()`, `timeIndex()`,
#' `channelNames()`, `defaultAssay()`.
#'
#' @section Channels, events and windows:
#' Channels `pickChannels()`, `dropChannels()`, `renameChannels()`,
#' `setChannelTypes()`, `setChannelUnits()`, `getChannelsByType()`; events
#' `addEvents()`, `getEvents()`, `removeEvents()`, `nEvents()`, `timeToSamples()`,
#' `samplesToTime()`; windows and combination `extractWindow()`, `cbindPhysio()`,
#' `rbindPhysio()`.
#'
#' @section Missing data, provenance and statistics:
#' NA handling `checkNA()`, `replaceNA()`, `naSummary()`; provenance
#' `provenance()`, `withProvenance()`, `logStep()`; reliability and effect-size
#' statistics `icc()`, `sem()`, `mdc()`, `cohensD()`, `blandAltman()`.
#'
#' @section Where to go next:
#' This package adds no functionality of its own; see the \pkg{PhysioExperiment}
#' documentation for the behaviour of every symbol above, and prefer depending on
#' \pkg{PhysioExperiment} in new code. A short orientation is in
#' `vignette("PhysioCore", package = "PhysioCore")`.
#'
#' @examples
#' # Everything works through the re-exported foundation API:
#' set.seed(1)
#' sig <- matrix(rnorm(500 * 3), nrow = 500, ncol = 3)
#' pe <- PhysioExperiment(assays = list(raw = sig), samplingRate = 250)
#' channelNames(pe) <- c("Fz", "Cz", "Pz")
#' samplingRate(pe)
#' nChannels(pe)
#' duration(pe)
#' pe <- addEvents(pe, onset = c(0.5, 1.2), duration = 0.1, type = "stimulus")
#' nEvents(pe)
#' seg <- extractWindow(pe, tmin = 0, tmax = 0.5)
#' dim(seg)
#'
#' @keywords internal
"_PACKAGE"
