# Generated by physio-ecosystem/publishing/generate_core_compat.R -- do not edit.

# Bind the foundation's S4 class metadata into this namespace so that the
# exportClasses() directives can re-export it: `exportClasses()` only
# registers a class whose metadata object lives in THIS namespace, and an
# imported class lives in the imports environment where the export machinery
# cannot see it.
#
# This runs at LOAD time on purpose. A top-level assign() would freeze a copy
# of each definition into the lazy-load database at build time, so upgrading
# the foundation would leave this package serving a stale definition.
.physio_reexported_classes <- c(
  "PhysioExperiment", "PhysioEvents", "MultiPhysioExperiment", "MultiRatePhysioExperiment", "PhysioLongitudinal", "PhysioCohort", "AnalysisResult", "PhysioBiomarker", "NormativeReference", "EventQuery"
)

.onLoad <- function(libname, pkgname) {
  ns <- asNamespace(pkgname)
  found <- asNamespace("PhysioExperiment")
  for (cl in .physio_reexported_classes) {
    nm <- methods::classMetaName(cl)
    assign(nm, get(nm, envir = found), envir = ns)
  }
}
